services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:4000/api
    depends_on:
      - backend
